-- ============================================================
--  Milestone by Zeus — v5: task numbers + "raised by"
--  Run ONCE, after supabase-v4-activity.sql. Safe to re-run.
--
--  1. tasks.seq        — a stable, human-readable number per task
--                        (shown as TSK-0001). Auto-assigned; existing
--                        tasks are backfilled in creation order.
--  2. tasks.created_by — who raised the task. Stamped by a trigger on
--                        insert (covers the UI and bulk imports) so it
--                        can't be forged or forgotten.
-- ============================================================

-- 1. Task number (identity backfills existing rows automatically) ----------
alter table public.tasks add column if not exists seq bigint generated by default as identity;

-- 2. Raised-by ------------------------------------------------------------
alter table public.tasks add column if not exists created_by uuid references public.employees(id) on delete set null;

create or replace function public.stamp_task_creator()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.created_by is null then
    new.created_by := public.my_employee_id();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_task_creator on public.tasks;
create trigger trg_task_creator
  before insert on public.tasks
  for each row execute function public.stamp_task_creator();
